17-rails-authentication/docoffice/config/routes.rb
Rails.application.routes.draw do
  # resources :doctors, only: [:index, :show, :new, :create, :edit, :update, :delete]
  resources :doctors
  resources :pills, only: [:new, :show, :create]

    # user account management
    get '/signup', to: 'users#new', as: 'signup'
    post '/signup', to: 'users#create'
    get '/users/:id', to: 'users#show', as: 'user'
  
    # sessions management
    get '/login', to: 'sessions#new', as: 'login'
    post '/sessions', to: 'sessions#create', as: 'sessions'
    post '/logout', to: 'sessions#destroy', as: 'logout'
  
end

17-rails-authentication/docoffice/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

17-rails-authentication/docoffice/app/models/doctor.rb
class Doctor < ApplicationRecord
  # https://edgeguides.rubyonrails.org/active_record_validations.html
  
  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true
  validates :specialty, presence: true

  has_many :pills, dependent: :destroy
  has_many :appointments
  has_many :patients, through: :appointments
end

17-rails-authentication/docoffice/app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
end

17-rails-authentication/docoffice/app/models/pill.rb
class Pill < ApplicationRecord
  belongs_to :doctor
end

17-rails-authentication/docoffice/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

17-rails-authentication/docoffice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      User.new
    end
  end

  def logged_in?
    !!current_user.id
  end

  def authorized?
    if !logged_in?
      flash[:authorized] = "you are not logged in"
      redirect_to login_path and return  # double redirect safeguard
    end
  end

  def authorized_for(target_user_id)
    if current_user.id != target_user_id.to_i && current_user.admin != true
      flash[:authorized] = "You cannot view a page that does not belong to you!"
      redirect_to doctors_path
    end
  end
end

17-rails-authentication/docoffice/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # github hack story https://gist.github.com/peternixey/1978249
  before_action :find_doctor, only: [:show, :edit, :update, :destroy]
  before_action :find_pills, only: [:new, :edit]
  before_action :authorized?, only: [:index, :show, :edit, :new]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def create
    @doctor = Doctor.create(doctor_params)
    if @doctor.valid?
      redirect_to doctors_path
    else
      flash[:errors] = @doctor.errors.full_messages
      redirect_to new_doctor_path
    end
  end

  def new
    @doctor = Doctor.new
  end

  def edit
  end

  def update
    @doctor.update(doctor_params)
    if @doctor.valid?
      redirect_to @doctor
    else
      flash[:errors] = @doctor.errors.full_messages
      redirect_to edit_doctor_path(@doctor)
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name, :specialty, pill_ids: [], patient_ids: [])
  end

  def find_doctor
    @doctor = Doctor.find(params[:id])
  end

  def find_pills
    @pills = Pill.all
  end
end

17-rails-authentication/docoffice/app/controllers/pills_controller.rb
class PillsController < ApplicationController
  before_action :authorized?, only: [:show, :new]

  def show
    @pill = Pill.find(params[:id])
  end

  def create
    @pill = Pill.new(pill_params)
    if @pill.valid?
      @pill.save
      redirect_to @pill
    else
      render 'new'
    end
  end

  def new
    @pill = Pill.new
  end

  private

  def pill_params
    params.require(:pill).permit(:name, :doctor_id)
  end
end

17-rails-authentication/docoffice/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to doctors_path
    else
      flash[:errors] = ["invalid username or password"]
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

17-rails-authentication/docoffice/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    authorized_for(params[:id])
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to doctors_path
    else
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

end

17-rails-authentication/docoffice/app/helpers/application_helper.rb
module ApplicationHelper
end

17-rails-authentication/docoffice/app/views/doctors/_form.html.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error_text| %>
      <li>
        <%= error_text %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>
    There is no errors!
  </p>
<% end %>


<%= form_for @doctor do |f| %>
  <span>👩‍⚕️👨‍⚕️🏥</span>
  <hr>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <hr>

  <%= f.label :specialty %>
  <%= f.text_field :specialty %>

  <p>select pills:</p>
  <%= f.collection_check_boxes :pill_ids, @pills, :id, :name %>

  <br>

  <p>select patients:</p>
  <%= f.collection_check_boxes :patient_ids, Patient.all, :id, :name %>

  <br>

  <%= f.submit %>

  <hr>
<% end %>

17-rails-authentication/docoffice/app/views/doctors/edit.html.erb
<h1> Edit doctor </h1>

<%= render 'form' %>

<%= form_tag doctor_path, method: "delete" do %>
  <%= submit_tag "delete that doctor" %>
<% end %>

17-rails-authentication/docoffice/app/views/doctors/index.html.erb
<h1>See all doctors</h1>

<%= link_to 'new doctor', new_doctor_path %>

<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor %>
    </li>
  <% end %>
</ul>

17-rails-authentication/docoffice/app/views/doctors/new.html.erb
<h1> New doctor form </h1>

<%= render 'form' %>

17-rails-authentication/docoffice/app/views/doctors/show.html.erb
<h1> <%= @doctor.name %> </h1>

<%= link_to 'edit', edit_doctor_path(@doctor) %>

<% if @doctor.pills %>
  <p>Pills:</p>
  <ul>
    <% @doctor.pills.each do |pill| %>
      <li>
        <%= pill.name %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>This doctor has no pills</p>
<% end %>

<% if @doctor.patients %>
  <p>Patients:</p>
  <ul>
    <% @doctor.patients.each do |patient| %>
      <li>
        <%= patient.name %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>This doctor has no patients</p>
<% end %>

<p>
  This doctor is good with <%= @doctor.specialty %>.
</p>

<%= link_to 'go back', doctors_path %>

17-rails-authentication/docoffice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docoffice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
    <h1>
      <%= link_to 'DOC APP👩‍⚕️🏥👨‍⚕️', doctors_path %>
    </h1>

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |e| %>
          <li style="color: red;">
            <%= e %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <% if flash[:authorized] %>
      <p style="color: red;">
        <%= flash[:authorized] %>
      </p>
    <% end %>

    <% if !logged_in? %>
      <%= link_to 'log in', login_path %>
      <%= link_to 'sign up', signup_path %>
    <% else %>
      <%= link_to "log out", logout_path, method: "post" %>
      <%= 'hello, ' + current_user.name + '!' %>
      <%= link_to 'my medical record', user_path(current_user) %>
    <% end %>
    <%= yield %>
  </body>
</html>

17-rails-authentication/docoffice/app/views/pills/new.html.erb
<%= form_for @pill do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.collection_select :doctor_id, Doctor.all, :id, :name %>

  <%= f.submit %>
<% end %>

17-rails-authentication/docoffice/app/views/pills/show.html.erb
<%= @pill.name %>

<%= link_to 'create more pills', new_pill_path %>

17-rails-authentication/docoffice/app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for @user, :url => "/signup" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

17-rails-authentication/docoffice/app/views/users/show.html.erb
<h2> <%= @user.name %> personal important information page </h2>

<%= link_to 'go back', '/doctors' %>